import localFont from 'next/font/local';
import "./globals.css";

//https://medium.com/@a.pirus/simplifying-multiple-fonts-styling-in-next-js-13-with-css-variables-cb57e9707693
// Font files can be colocated inside of `app`
const generalSans = localFont({
  src: '../fonts/body/GeneralSans-Variable.woff2',
  display: 'swap',
  variable: '--font-generalSans'
})
const satoshi = localFont({
  src: '../fonts/header/Satoshi-Variable.woff2',
  display: 'swap',
  variable: '--font-satoshi'
})
export const metadata = {
  title: "Rayyan | Web Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${generalSans.variable}`}>{children}</body>
    </html>
  );
}
